#!/usr/bin/env bash
# Renders the ACTIVE waybar files (config.jsonc / style.css) from the sources in
# configs/ and styles/, applying the current mode (.mode) and scale factor (.scale).
#
# Waybar is GTK3 and has no scale setting, so "scaling" means multiplying every px value in
# the CSS, the bar height/margins in the config, and the inline Pango <span size='...'>
# values. Doing it at render time keeps configs/ and styles/ as a clean 1.0 baseline --
# scaling is never applied on top of itself, so it stays lossless and repeatable.
#
# Usage: render.sh          (re-render using current .mode and .scale)
set -euo pipefail

DIR="$HOME/.config/waybar"
MODE=$(cat "$DIR/.mode" 2>/dev/null || echo bar)
SCALE=$(cat "$DIR/.scale" 2>/dev/null || echo 1.0)

case "$MODE" in bar|dock) ;; *) MODE=bar ;; esac
# Reject anything that isn't a plain positive number, then clamp to a sane range.
[[ "$SCALE" =~ ^[0-9]+(\.[0-9]+)?$ ]] || SCALE=1.0
awk -v s="$SCALE" 'BEGIN{exit !(s>=0.5 && s<=3.0)}' || SCALE=1.0

SRC_CONFIG="$DIR/configs/$MODE.jsonc"
SRC_STYLE="$DIR/styles/$MODE.css"
WARN="AUTO-GENERATED by render.sh -- edits here are DESTROYED on the next mode/scale change."

scale_css() {
    perl -pe 'BEGIN{$s=shift @ARGV} s/(\d+(?:\.\d+)?)px/sprintf("%gpx", $1*$s)/ge' "$1" "$2"
}

scale_jsonc() {
    # Only size-bearing keys are scaled. Never touch "interval", "signal", "timeout", etc.
    # These are all integer-valued in waybar (a fractional "height" is not accepted), and
    # Pango sizes are integer 1/1024ths, so round rather than truncate -- plain int() turned
    # 11500 * 1.15 into 13224 instead of 13225.
    perl -pe 'BEGIN{$s=shift @ARGV}
        s/("(?:height|border-radius|icon-size|spacing|margin-(?:top|bottom|left|right))"\s*:\s*)(\d+(?:\.\d+)?)/$1 . int($2*$s + 0.5)/ge;
        s/size='"'"'(\d+)'"'"'/sprintf("size=%c%d%c", 39, int($1*$s + 0.5), 39)/ge;
    ' "$1" "$2"
}

{ printf '// %s Edit configs/%s.jsonc instead.\n' "$WARN" "$MODE"; scale_jsonc "$SCALE" "$SRC_CONFIG"; } > "$DIR/config.jsonc"
{ printf '/* %s Edit styles/%s.css instead. */\n' "$WARN" "$MODE"; scale_css "$SCALE" "$SRC_STYLE"; }  > "$DIR/style.css"
