$font = JetBrainsMono Nerd Font Propo
$text_color = rgba(242, 244, 248, 0.95)
$text_color_sub = rgba(242, 244, 248, 0.70)
$accent_color = rgba(120, 169, 255, 1.0)
$accent_color_alpha = rgba(120, 169, 255, 0.35)
$error_color = rgba(237, 135, 150, 1.0)
$inner_color = rgba(18, 18, 18, 0.65)

general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
}

background {
    monitor =
    path = /home/xaccefy/.cache/hyprlock_wallpaper
    color = rgba(17, 17, 27, 1.0)
    blur_passes = 2
    blur_size = 4
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 0
    animation = fadeOut, 1, 2, linear
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $text_color
    font_size = 90
    font_family = JetBrainsMono Nerd Font Propo Bold
    position = 0, 150
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 4
    shadow_color = rgba(0, 0, 0, 0.5)
}

# Date
label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %d %B")"
    color = $text_color_sub
    font_size = 20
    font_family = JetBrainsMono Nerd Font Propo Medium
    position = 0, 74
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 3
    shadow_color = rgba(0, 0, 0, 0.5)
}

# Password Input
input-field {
    monitor =
    size = 300, 52
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    dots_rounding = -1
    outer_color = $accent_color_alpha
    inner_color = $inner_color
    font_color = $text_color
    fade_on_empty = false
    placeholder_text = <i><span foreground="##f2f4f8ba">Password...</span></i>
    hide_input = false
    rounding = 14
    fail_color = $error_color
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $accent_color
    numlock_color = $accent_color
    bothlock_color = $accent_color
    check_color = $accent_color
    check_text = <i>Checking…</i>
    position = 0, -30
    halign = center
    valign = center
}

# Layout
label {
    monitor =
    text = 󰌌  $LAYOUT
    color = $text_color_sub
    font_size = 11
    font_family = JetBrainsMono Nerd Font Propo
    position = 30, 20
    halign = left
    valign = bottom
}
