# -----------------------------------------------------
# Environment Variables
# -----------------------------------------------------

# https://wiki.hyprland.org/Nvidia/
# Apps
env = MOZ_ENABLE_WAYLAND,1
env = GTK_CSD,0

env = XDG_SESSION_TYPE,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto

cursor {
    no_hardware_cursors = true
}
