# -----------------------------------------------------
# Layouts
# -----------------------------------------------------
general {
    layout = scrolling
}

dwindle {
    pseudotile = true
    preserve_split = true
}
