# -----------------------------------------------------
# Layouts
# -----------------------------------------------------
# General layout setting moved to window.conf

dwindle {
    pseudotile = true
    preserve_split = true
}
