# -----------------------------------------------------
# Scrolling layout (Hyprland 0.54+)
# https://wiki.hypr.land/Configuring/Scrolling-Layout/
# -----------------------------------------------------
scrolling {
    column_width = 0.5
    focus_fit_method = 1
    follow_focus = true
    follow_min_visible = 0.4
    direction = right
}
