# -----------------------------------------------------
# General window decoration
# -----------------------------------------------------

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(78a9ffee) rgba(be95ffee) 45deg
    col.inactive_border = rgba(262626aa)
    layout = scrolling
}
