# -----------------------------------------------------
# General window decoration
# -----------------------------------------------------

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 1
    col.active_border = rgba(f2f4f8cc)
    col.inactive_border = rgba(525252aa)
    layout = dwindle
}

layerrule = blur true, match:namespace ^(waybar)$

windowrule = float true, match:title ^(Picture-in-Picture)$
windowrule = pin true, match:title ^(Picture-in-Picture)$
windowrule = size 480 270, match:title ^(Picture-in-Picture)$
windowrule = move 100%-500 40, match:title ^(Picture-in-Picture)$
windowrule = float true, match:title ^(Open File)(.*)$
windowrule = float true, match:title ^(Save File)(.*)$
windowrule = float true, match:title ^(Choose File)(.*)$
windowrule = float true, match:title ^(Authentication Required)(.*)$
windowrule = float true, match:class ^(pavucontrol)$
